name: flutter_plugin_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.0.7
author: Tiago Ribeiro <tiagopribeiro.1992@gmail.com>
homepage: https://github.com/CrossPT/flutter_plugin_pdf_viewer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  flutter_cache_manager: ^2.1.1
  numberpicker:
  flutter_advanced_networkimage:
    # path: /Users/sookshumlabs/Documents/GitHub/flutter_advanced_networkimage-1
    git: https://github.com/anil-sookshum/flutter_advanced_networkimage-1

flutter:
  plugin:
    androidPackage: pt.tribeiro.flutter_plugin_pdf_viewer
    pluginClass: FlutterPluginPdfViewerPlugin
